PRAGMA foreign_keys = ON;
CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL, name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), csrf TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE oauth_states (id TEXT PRIMARY KEY, kind TEXT NOT NULL, user_id TEXT, nonce TEXT NOT NULL, verifier TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE credentials (user_id TEXT NOT NULL REFERENCES users(id), provider TEXT NOT NULL, envelope TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(user_id,provider));
CREATE TABLE accounts (user_id TEXT NOT NULL REFERENCES users(id), platform TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY(user_id,platform));
CREATE TABLE settings (user_id TEXT PRIMARY KEY REFERENCES users(id), data TEXT NOT NULL);
CREATE TABLE media (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), object_key TEXT NOT NULL UNIQUE, name TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX media_owner ON media(user_id,created_at);
CREATE TABLE uploads (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), object_key TEXT NOT NULL UNIQUE, upload_id TEXT NOT NULL, name TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending', expires_at INTEGER NOT NULL);
CREATE INDEX uploads_owner ON uploads(user_id,status,expires_at);
CREATE TABLE posts (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), media_id TEXT NOT NULL REFERENCES media(id), title TEXT NOT NULL, caption TEXT NOT NULL, status TEXT NOT NULL, scheduled_for TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT);
CREATE INDEX posts_owner ON posts(user_id,created_at);
CREATE INDEX posts_due ON posts(status,scheduled_for);
CREATE TABLE targets (post_id TEXT NOT NULL REFERENCES posts(id), platform TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', data TEXT NOT NULL DEFAULT '{}', error TEXT, PRIMARY KEY(post_id,platform));
CREATE TABLE runs (id TEXT PRIMARY KEY, post_id TEXT NOT NULL REFERENCES posts(id), status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, dispatched_at TEXT, finished_at TEXT);
CREATE UNIQUE INDEX one_active_run ON runs(post_id) WHERE status IN ('pending','dispatched');
CREATE INDEX runs_pending ON runs(status,created_at);
CREATE TABLE attempts (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), platform TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL);
